# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1e4b477d9c1066b6403f3c3210ffad3fbe85e0545da5091cb2b723f8256e1d2815044be47805acca0cbe71833ad17a54a6818ef4f78e7a91d7118d051a6a336

test:
  secret_key_base: 6507949271af5fddb6e043ee5b3f0216da6b22f3151854e3b77383e91d7d324ef02369d735916e9195ccbb5c7c65fd44ef9482889088a2f7ee17ef4de625f8fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
